### ISSUE TITLE
Coordinate Grid brushing staggered

### ISSUE THREAD

**Issue by mtraynham** [dc-js/dc.js#973]
Hey Gordon,

You added a recent change to the [renderBrush](https://github.com/dc-js/dc.js/compare/c3d9ee99baedeffd63be0f55771690c7b655f567...f309dea7d7a1c06f53de50d8886ba90ed2a206bf#diff-217c6713cc2eaafedb69acf173c78760R936) function, but I think this actually makes the [brushing](https://github.com/dc-js/dc.js/blob/develop/src/coordinate-grid-mixin.js#L910) event worse.

My proposal is to remove the call to `redrawBrush` from the `_chart._brushing` method at https://github.com/dc-js/dc.js/blob/develop/src/coordinate-grid-mixin.js#L913.  It seems unnecessary to "redraw" the brush if the event itself **is** redrawing the brush.  The change you made just amplifies this issue because the redraw now happens with a  transition and likely during a user brush.  Feel free to clarify if there is a reason it should be calling that method.  It likely still needs to call the `_chart.fadeDeselectedArea();` at https://github.com/dc-js/dc.js/blob/develop/src/coordinate-grid-mixin.js#L944.

**Comment by gordonwoodhull** [comment]
Hi @mtraynham. You are right, it shouldn't be transitioned when in response to a mouse event. I hadn't noticed that.

I'm not sure why the `redrawBrush` is there; it was introduced in 309a2f47cb6bf5d29d436c3c5d31204da17eb22a and apparently has something to do with event throttling.

I'll fix it one way or the other today.

**Comment by gordonwoodhull** [comment]
So... disabling that `redrawBrush` is not sufficient, as bits and pieces of the brush are still transitioned.

I've pushed a branch `no-transition-brush` which only transitions the brush in the chart resize/rescale case. Could you check that this works for you?

**Comment by gordonwoodhull** [comment]
I think the more general way to code this would probably be to pass down a d3 selection from the events that actually know whether transitions are needed or not - this selection would be either transitioned or not and all subselections would inherit from it. Rather than each piece of code starting from scratch with its own selection and deciding whether to transition or not. 

It's kind of a big refactor, though.

**Comment by mtraynham** [comment]
Ehh sort of, I still see it happening with Composite charts, usually through this stack trace:

[_chart._brushing()](https://github.com/dc-js/dc.js/blob/no-transition-brush/src/coordinate-grid-mixin.js#L918)
[_chart.redrawGroup()](https://github.com/dc-js/dc.js/blob/no-transition-brush/src/base-mixin.js#L530)
[drawChart()](https://github.com/dc-js/dc.js/blob/no-transition-brush/src/coordinate-grid-mixin.js#L1030)
[_chart._prepareYAxis](https://github.com/dc-js/dc.js/blob/no-transition-brush/src/composite-chart.js#L91)
[_chart.y(_)](https://github.com/dc-js/dc.js/blob/no-transition-brush/src/coordinate-grid-mixin.js#L669)
[_chart.rescale()](https://github.com/dc-js/dc.js/blob/no-transition-brush/src/coordinate-grid-mixin.js#L111)
[drawChart()](https://github.com/dc-js/dc.js/blob/no-transition-brush/src/coordinate-grid-mixin.js#L1045)

**Comment by gordonwoodhull** [comment]
I see, the problem here being that setting the Y scale falsely registers as a rescale. This looks like a good fix because it will help toward supporting non-linear scales for elasticY. Thanks!

**Comment by mtraynham** [comment]
Not a problem.  After trying my change out, everything on your `no-transition-brush` branch seems like it works fluently.  Although, I'm still a bit lost on why we need to call that `redrawBrush` method from `_brushing`.  `_brushing` usually triggers a redraw of the chart group, and the chart that was "brushed" will get redrawn thus invoking `redrawBrush` a second time.

**Comment by gordonwoodhull** [comment]
Aha, I think it is for brush rounding - the first line in `_brushing` calls `extendBrush`, which rounds the extent (e.g. to months). Then the brush needs to be redrawn. 

So it's unrelated to the commit message, just another fix that went into the same commit.

**Comment by gordonwoodhull** [comment]
Wow, breaks 20 tests. Hold on.

**Comment by mtraynham** [comment]
Oof.

**Comment by gordonwoodhull** [comment]
Aha:
```{javascript}
        if (_chart.y() === undefined || _chart.elasticY()) {
            if (_chart.y() === undefined) {
                _chart.y(d3.scale.linear());
            }
            _chart.y().domain([yAxisMin(), yAxisMax()]).rangeRound([_chart.yAxisHeight(), 0]);
            _chart.rescale();
        }
```
etc.

**Comment by mtraynham** [comment]
Ahh good catch!  Didn't set the domain for null undefined y scales.

**Comment by mtraynham** [comment]
Hey thanks Gordon!  By the way, looking at the commit:
https://github.com/dc-js/dc.js/commit/9b4242a75afdd05e460967ff42c343fca37168b7#diff-220a8baefc3911d2f47ce06b66f53338R5988

Shows the old way I recommended.  Not a big deal, just make sure you push the latest web build up when you commit next time :smile:

**Comment by gordonwoodhull** [comment]
Hmm, I think this may be the fix for #808 biting us again. 

Not building the docs by default can lead to lots of stuff out of sync.

**Comment by gordonwoodhull** [comment]
I also rebroke the resizing of composite charts, fixing this. :frowning: 

Most likely transitions canceling each other out.
